FROM oraclelinux:6.10

USER root

# Expose SSH Ports 
#
EXPOSE 22 

# Add Oracle user and groups and update sudoers
#
RUN groupadd -g 501 oinstall \
  && groupadd -g 502 dba \
  && groupadd -g 503 oper \
  && groupadd -g 504 asmadmin \
  && groupadd -g 505 asmdba \
  && groupadd -g 506 asmoper \
  && groupadd -g 507 bkpdba \
  && groupadd -g 508 dgdba \
  && groupadd -g 509 kmdba \
  && useradd -m -g oinstall -G oinstall,dba,oper,asmadmin,asmdba,bkpdba,dgdba,kmdba -u 501 oracle 

# Add a few additional packages
# remove nodocs to allow for man pages to be installed
#
RUN sed -i '/tsflags=nodocs/d' /etc/yum.conf \
 && rpm --rebuilddb \
 && yum -y --enablerepo=ol6_latest,ol6_optional_latest install patch bc binutils bzip2 bzip2-devel dos2unix gcc gcc-c++ glibc-static gzip libaio libgcc libstdc++ libstdc++-devel lsof make man man-pages net-tools nss-devel perl strace subversion sudo sysstat tar tree unix2dos unzip wget which zip zlib zlib-devel zlib-static gettext tcl tcl-devel openssh openssh-server xclock xhost psmisc xorg-x11-fonts* xorg-x11-server-Xvfb.x86_64 xterm libvncserver xorg-x11-server-devel avahi-libs tk libXtst mesa-dri-drivers xorg-x11-utils screen bind-libs bind-utils compat-libcap1 compat-libstdc++-33 e2fsprogs-libs ethtool gssproxy keyutils ksh libaio-devel libbasicobjects libcollection libevent libini_config libnfsidmap libpath_utils libref_array libtirpc libverto-libevent mailx nfs-utils quota quota-nls rpcbind smartmontools tcp_wrappers gdb patch jq \
 && yum clean all \
 && rm -rf /var/cache/yum/*


# Update sudoers and create directories:
#
RUN echo "oracle           ALL=(ALL)       NOPASSWD:ALL" >> /etc/sudoers \
  && echo "Defaults !requiretty"  >> /etc/sudoers \
  && mkdir /install \ 
  && mkdir -p /u01/app/oracle \
  && mkdir -p /home/oracle/bin \
  && chown -R oracle:oinstall /u01/app \
  && chown -R oracle:oinstall /install \
  && chown -R oracle:oinstall /home/oracle/bin

# set entrypoint and run default bash command
#
CMD ["/bin/bash"]


